src/cfitsio.jl
Same changes as before plus fix of unitialized variable `nelements` in `fits_read_col` and `fits_write_col`.
=> Pull request/1a150c30

NEWS.md, src/FITSIO.jl, src/cfitsio.jl, src/deprecations.jl, src/hdutypes.jl, test/runtests.jl
This depends on #22. I'll rebase this once we merge that PR. The first two commits are in #22; only the last commit here, 2dc0f5f, is new. Just look at that.
=> Fix v0.4 deprecation warnings

REQUIRE, src/cfitsio.jl
this quick fix prevents error in ColumnDef with recent v0.4
=> explicitly use Tuple with typealias ColumnDef

src/header.jl
For [Issue 39](https://github.com/JuliaAstro/FITSIO.jl/issues/39).
=> Read raw header from an HDU

src/header.jl, test/runtests.jl
Hey Kyle,
I'm sorry, there was a bug in my read_header.  I made a fix and added a test.
Ryan
=> read_header raw string bug fix

src/FITSIO.jl, src/fits.jl, src/header.jl, src/image.jl, src/libcfitsio.jl, src/table.jl, test/runtests.jl
Hi Kyle, This PR fixes all the deprecated warnings from FITSIO.jl caused by the recent changes to Julia 0.4.
=> Fixes Julia 0.4-rc2 warnings 

.travis.yml, appveyor.yml
as long as REQUIRE says it's supported
=> also run travis on 0.3

src/header.jl
=> remove BUNIT from reserved keys

REQUIRE, deps/build.jl, src/FITSIO.jl, src/fits.jl, src/header.jl, src/image.jl, src/libcfitsio.jl, src/table.jl, test/runtests.jl
Hi @kbarbary  -- This fixes the vast majority of warnings from Julia 0.5, without breaking any backward compatibility, I think.
=> fix warnings from Julia 0.5 

deps/build.jl, src/libcfitsio.jl
... and also add `--enable-reentrant` in build script while we're at it.
=> Fix cfitsio_typecode() method redefinition

.travis.yml, deps/build.jl
and use the apt addon so `apt-get install` doesn't try to run on mac
and turn on 0.4 and 0.5 on Travis, since `release` will change meaning soon
0.5 runs the latest RC right now, will change to latest release once final is out
=> enable osx on Travis

src/FITSIO.jl, test/runtests.jl
This is like the `open` method that automatically close the file upon completion: https://docs.julialang.org/en/latest/manual/networking-and-streams.html#Working-with-Files-1
=> Provide FITS method that automatically closes file

test/libcfitsio.jl
Addresses https://github.com/JuliaAstro/FITSIO.jl/commit/c2c3fd610471d0461bda5342fd1287d68156cefd#commitcomment-22529623.
=> clean up temp file in healpix test

src/FITSIO.jl
The large work-in-progress PR will come in a while, but I wanted to use this minor PR as a trial run to show how the documentation will look like (some elements are similar to AstroLib.jl).
=> Trial documentation shift

docs/mkdocs.yml
This...should make everything work. Hopefully.
=> Documenter Theme Patch

src/FITSIO.jl, src/header.jl, src/libcfitsio.jl, src/table.jl
Fix #75.
I think I addressed most cases, but a review is required.
No test yet.
=> Assert strings written to file are ASCII

NEWS.md, src/libcfitsio.jl, src/table.jl, test/runtests.jl
Add an optional keyword to select the behavior.  Fix #98.
=> Make fits_get_colnum case sensitive by default

docs/src/api.md, docs/src/index.md, src/image.jl, test/runtests.jl
Added a feature discussed in #116.
=> Write data to an existing image HDU

.drone.jsonnet, .drone.yml
This enables running tests on ARM architecture
=> Add Drone CI scripts

docs/src/api.md, src/FITSIO.jl, src/image.jl, test/runtests.jl
Fixes #147 
Now 
```julia
julia> FITS("temp.fits", "w") do f
write(f, zeros(Int32, 2))
end
julia> FITS("temp.fits", "r") do f
eltype(f[1])
end
Int32
```
=> Obtain eltype of an ImageHDU

README.md
=> Fix the link to dev docs in Readme

docs/src/index.md
Add a tip in the docs describing the automatic data compression feature inbuilt in cfitsio. This can significantly reduce the file sizes of images saved to disk.
=> Add tip about compressed files

src/FITSIO.jl, src/header.jl, test/runtests.jl
Hi, 
I need to delete keywords in FITSHeaders relatively frequently so I implemented a deletekey function which perhaps is of interest. This PR has that implemented as well as adding it to exports and putting in a simple test case.
=> Delete key in FITSHeader

Project.toml
Version bump requested by @aplavin on #200. Will leave open for a bit in case anyone wishes to comment.
=> bump version to 0.17.4

.github/workflows/TagBot.yml
See https://github.com/JuliaRegistries/TagBot/pull/392.
=> [CI] Fix TagBot setup

src/FITSIO.jl
This makes the code more readable
=> CFITSIO read/write mode enum in `FITS`

Project.toml
Also add some missing compat entries.
=> Bump Aqua to v0.8

Project.toml, docs/src/api.md, src/FITSIO.jl, src/fits.jl, src/image.jl, src/table.jl, test/runtests.jl
This lets us vrify the integrity of the HDU
=> Write and verify checksum
