NEWS.md, src/FITSIO.jl, src/cfitsio.jl, src/deprecations.jl
- move the definitions of `fits_get_coltype`, `fits_get_eqcoltype`, `fits_read_tdim` to earlier in the file so that `fits_get_coltype` can be used in `fits_read_col` instead of the deprecated function `fits_get_col_repeat`.
- move deprecated functions/methods to a separate file `deprecations.jl` and use the `@deprecated` macro to emit a deprecation warning.
@emmt should review this. Tests pass locally but there's no tests for the table functions yet, so it is not a very good indicator!
=> emit warnings for deprecated functions

src/cfitsio.jl, src/hdutypes.jl, test/runtests.jl
This is a simple fix for #24. To explain: cfitsio returns header values as strings. In the high-level interface `FITSHeader`, we parse these strings into their implied types, for convenience. First we try to parse as an int, then a float, then a bool, then nothing, then a string (if value is surrounded by `'`). What to do when we get to the end? Formerly we raised an error saying that the value couldn't be parsed. This PR changes the behavior to simply return the unparsed string.
The upside of the change is that a single malformed keyword will no longer prevent one from reading the entire header. The slight downside is that you can't tell if the original unparsed value was a correctly quoted string or a malformed value that we gave up parsing. The upside outweighs the downside, but it …
=> non-standard header values

src/hdutypes.jl
A few changes to:
* have methods like `readheader` and `readkey` also available at the low level interface;
* fix a bug in `readheader` (buffer overflow) when dealing with keywords longer than 8 characters (e.g. HIERARCH keywords), the 3 byte buffers are now large enough to store the complete FITS card (which is safe although probably too large but that's only 3x81 bytes....);
* optimize `parse_header_val` (having the try...catch statements used in last resort) and remove trailing spaces in string vales (according to FITS convetion that trailing spaces are insignificant).
=> a few fixes

src/cfitsio.jl, src/hdutypes.jl
Hi Kyle,
I hope you don't mind that I'm just making the pull request for the ccall part, it might be easier for you to organize the read() function in a way that suits everybody.
Ryan
=> Fits read descriptll

LICENSE, NEWS.md, README.md, doc/api.rst, src/cfitsio.jl, src/hdutypes.jl, test/runtests.jl
On reading, variable-length columns are automatically read into `Vector{Vector{T}}` or `Vector{ASCIIString}` (for string columns).
On writing a new table, the `varcols` keyword can be used to specify which columns should be written as variable length. This is necessary because `Vector{ASCIIString}` can go either way. Other types must be vectors of vectors in order to be written as variable-length.
=> Read/write variable-length table columns

.travis.yml, NEWS.md, README.md, appveyor.yml, deps/build.jl, src/fits.jl, src/header.jl, src/libcfitsio.jl, test/runtests.jl
@tkelman's JuliaCon talk inspired me to start supporting Windows. In this case, it should be pretty easy because there are pre-built windows binaries for cfitsio on the cfitsio homepage.
I don't expect this PR to work immediately, as I've probably got the BinDeps build script wrong. This is mainly to try AppVeyor out.
Quick question for Tony: The [cfitsio homepage](http://heasarc.gsfc.nasa.gov/docs/software/fitsio/) provides both MSVC and Borland binaries. Do we have to worry about using the later? (I have no experience with Windows!)
=> Windows support

src/image.jl
This fixes tests on Julia v0.5, by making `read(hdu, 1, 1:10)` return an `Array{T, 1}` instead of `Array{T, 2}`, in line with how `data[1, 1:10]` now works.
It would probably be good to have a more precise version for this change if anyone knows it. Right now the test is just  `VERSION >= v"0.5.0-dev"`.
=> fix scalar indexing in Julia 0.5

deps/build.jl
=> fix use of cp on windows build

.travis.yml, REQUIRE, appveyor.yml, src/fits.jl, src/header.jl, src/image.jl, src/libcfitsio.jl, src/table.jl, test/runtests.jl
Mainly the deprecation of the old `Array` constructor. I'm also using `Ref` in `ccall`s whenever possible. Finally, I'm dropping Julia 0.3 support since some of these changes won't work there and I don't think it is relevant to support anymore.
=> Updates for Julia 0.6

src/FITSIO.jl, src/fits.jl, src/header.jl, src/libcfitsio.jl, test/runtests.jl
Support read-only memory backed files via `ffomem`. Also clean up a couple of deprecations
while I'm here.
=> Support memory backed files

src/header.jl, src/image.jl
A typo in variable names may be tolerable, but the word was misspelled also in
an error message, so I fixed it everywhere.
=> Fix typo: indicies → indices

deps/build.jl, src/FITSIO.jl, src/fits.jl, src/header.jl, src/image.jl, src/libcfitsio.jl, src/table.jl, test/runtests.jl
I don't know what the `@compat` macro is used for in the definitions of `ColumnDef` and `FITSTableScalar`, can be removed?
=> Clear deprecation warnings in Julia 0.6

src/FITSIO.jl, test/runtests.jl
Add an optional argument to `libcfitsio_version` which defaults to `fits_get_version()`, so that it’s possible to test how the function parses a number as a VersionNumber.
This should prevent silly PR like #64 in the future :-D
=> Test libcfitsio_version

src/libcfitsio.jl, test/libcfitsio.jl, test/runtests.jl
I am currently in the processing of rewriting a lot of LibHealpix.jl.
One of its limitations has been that it uses the libchealpix functions
to read and write Healpix maps as FITS images. These functions only work
with Float32 values, so we were frequently discarding precision when
doing I/O with Healpix maps.
To remedy that situation I am replacing this part of the wrapper with
the FITSIO Libcfitsio interface. This makes it easy for me to port the
original C functions into Julia.
This commit adds some missing functionality that I needed to make this
work:
* wrap `fits_read_key_str`
* wrap `fits_read_key_lng`
* wrap `fits_read_keys_lng`
* wrap `fits_write_date`
* widen the signature of `fits_write_key` to accept all `Number`s
ref issue JuliaAstro/FITSIO.jl#61
=> additional functionality needed for LibHealpix.jl

.travis.yml, NEWS.md, REQUIRE, appveyor.yml, src/FITSIO.jl, src/fits.jl, src/header.jl, src/image.jl, src/libcfitsio.jl, src/table.jl
`Compat.jl` dropped support for Julia 0.4, so it's probably time to do the same here.
Note that `String` type doesn't guarantee there are only ASCII character in the string.  If necessary, that should be tested with `isascii`.
=> Drop support for Julia 0.4

src/FITSIO.jl, src/header.jl, src/table.jl
Only warnings about `type` keyword are issued now, but this isn't supported in `Compat.jl`.
=> Clear deprecation warnings in Julia 0.7

REQUIRE, deps/build.jl
I don't have easy access to a Mac so this is untested. Hopefully Travis comes back with a green light.
This *might* fix some of the issues reported in mweastwood/LibHealpix.jl#38, but I think this is a good idea regardless.
=> use Homebrew.jl to grab cfitsio on OSX

docs/make.jl, docs/mkdocs.yml, docs/src/index.md
#77 doesn't build docs due to an error cause by missing `mkdocs.yml` file. Additionally, in the same PR a lack of content for `index.md` was pointed out. PR to resolve the same.
=> Make Documenter build successfully

src/fits.jl, src/header.jl, src/image.jl, src/table.jl, test/runtests.jl
Usually `show` methods don't add a newline at the end, as the Julia REPL automatically prints it.
There are no tests, should I add them?
=> Do not print newline at the end of show methods

docs/src/index.md
Trying to install FITSIO on a clean debian system running Julia Version 0.4.7 I had to remove the .jl extension when adding the package.
=> edited possible error in install instructions

.travis.yml, REQUIRE, appveyor.yml, src/FITSIO.jl, src/libcfitsio.jl
There are still some errors on Julia 0.7 that need to be addressed.
=> Drop support for unmaintained Julia 0.5

docs/src/api.md, docs/src/index.md, src/table.jl, test/runtests.jl
Here is my take to close #93.
A couple of comments:
* I'm not sure whether the `colnames` function should be exported
* There are no test about showing an `ASCIITable`.  Why `f[3]` in the "Tables" test set can't be shown?
=> Add method to get colum names in FITS tables

src/table.jl, test/runtests.jl
Use a `try`-`catch` block to issue the warnings.  Ref. #98.
This is done only for `read` because it's the user-visible function.  I don't see how we can issue the warning only once if it's also inside `fits_get_colnum`.
I'd also like to add a couple of tests to make sure that the warning is emitted in the correct case, but I can't make `@test_warn` and `@test_nowarn` work.  If anyone has a clue about how to do this, please share!
=> Issue deprecation warning for read(::TableHDU, ::String) with no keyword

src/FITSIO.jl, src/header.jl, test/runtests.jl
The base method `getkey` is extended so that `getkey(hdr, key, def)` can be called with `hdr` being an instance of `FITSHeader`.
=> Extend `getkey` for `FITSHeader`

Project.toml, src/FITSIO.jl, src/image.jl, src/libcfitsio.jl, test/runtests.jl
This PR lets us read and write complex arrays that are reinterpreted as floating point ones (addresses #129). Eg:
```julia
julia> FITS("temp.fits","w") do f
write(f, reinterpret(Float64, ones(ComplexF64,3,3) ) )
end
julia> FITS("temp.fits","r") do f
read(f[1])
end
6×3 Array{Float64,2}:
1.0  1.0  1.0
0.0  0.0  0.0
1.0  1.0  1.0
0.0  0.0  0.0
1.0  1.0  1.0
0.0  0.0  0.0
julia> FITS("temp.fits","r") do f
reinterpret(ComplexF64,read(f[1]))
end
3×3 reinterpret(Complex{Float64}, ::Array{Float64,2}):
1.0+0.0im  1.0+0.0im  1.0+0.0im
1.0+0.0im  1.0+0.0im  1.0+0.0im
1.0+0.0im  1.0+0.0im  1.0+0.0im
julia> a = zeros(ComplexF64,3,3);
julia> FITS("temp.fits","r") do f
read!(f[1], reinterpret(Float64,a))
end;
julia> a
3×3 Array{Complex{Float64},2}:
1.0+0.0im  1.0+0.0im  1.0+0.0im
1.0+0.0im  1.0+0.0im …
```
=> Read and write complex arrays + limit compat version bounds

src/FITSIO.jl, src/image.jl, src/libcfitsio.jl, test/runtests.jl
Following the discussion in #131 , this is an initial attempt to replace the messy unions of contiguous types by `StridedArray`s. The `cfitsio` library seems to require a contiguous memory layout for the arrays to be written and read into, however AFAIK there isn't an obvious contiguous `StridedArray` type to dispatch on. To get around this currently we carry out a runtime check to ensure that the strides along the various axes are compatible with a contiguous layout. For the most part this seems to work, however further tests might be warranted.
```julia
julia> fitsfile=tempname();
julia> b = reshape([1:8;],2,2,2);
julia> b_view = @view b[:,:,1]
2×2 view(::Array{Int64,3}, :, :, 1) with eltype Int64:
1  3
2  4
julia> FITS(fitsfile,"w") do f
write(f, b_view)
end
julia> FITS(fitsfile,"r") …
```
=> read and write StridedArrays as images

Project.toml, src/FITSIO.jl, src/header.jl, test/runtests.jl
Added this method to get default header of an `AbstractArray`, it is being used in `CCDReduction.jl` to create `CCDData` directly from an `AbstractArray`. E. g.
```
CCDData(data::AbstractArray) = CCDData(data, get_default_header(data))
```
=> Added method to get default header for `AbstractArray`

Project.toml, README.md
The version was incremented to v0.16.2 to use the `default_header` in `CCDReduction.jl`
=> minor readme fix and bumped version

docs/src/api.md, src/header.jl, src/image.jl, src/table.jl, test/runtests.jl
These convenience functions are useful while working with images. Currently I find this pattern commonly used in my code:
```julia
FITS(filename, "r") do f
read(f[1])
end
```
this may be replaced by 
```julia
fitsread(filename)
```
and similarly for writing as well. This is easier for REPL usage too.
Not sure if these should be exported (possible conflicts in case users have defined these themselves), so currently it's up to the users to import these.
=> Add fitsread and fitswrite

test/runtests.jl
Since `CFITSIO.jl` has now introduced its own error type `CFITSIOError`, tests that checked for `ErrorException` specifically are failing. This PR fixes these (along with the [upstream fix](https://github.com/JuliaAstro/CFITSIO.jl/pull/5)). Tests appear to pass locally for me.
The CI will need to be re-triggered once the patch to `CFITSIO.jl` is released.
=> Bugfix in exception type check in tests

Project.toml, src/FITSIO.jl, src/image.jl, test/runtests.jl
This helps make the `size` and `read` functions type-stable.
After this PR:
```julia
julia> fname = tempname() * ".fits"
"/tmp/jl_sFQ6s6.fits"
julia> FITS(fname, "w") do f
write(f, ones(2,2))
end
julia> f = FITS(fname);
julia> @code_warntype read(f[1])
Variables
[...]
Body::Array{Float64,2}
[...]
julia> @code_warntype size(f[1])
Variables
[...]
Body::Tuple{Int64,Int64}
[...]
```
As a consequence:
on master:
```julia
julia> FITS(fname, "w") do f
write(f, ones(100, 100))
end
julia> f = FITS(fname,"r");
julia> @btime read($(f[1]));
39.639 μs (12 allocations: 78.89 KiB)
```
After this PR:
```julia
julia> @btime read($(f[1]));
23.956 μs (5 allocations: 78.48 KiB)
```
The time difference is not significant for large arrays though when reading from disk dominates the execution time.
2. this PR …
=> Make ImageHDU parametric

Project.toml, src/FITSIO.jl, test/runtests.jl
This restores the possibility of indexing an Image HDU with a string.
Fix #163.  CC: @jishnub @andrew-saydjari
=> Loosen signature of `ImageHDU` inner constructor

src/image.jl
The PR is best viewed by ignoring the whitespace fixes. The main changes are in https://github.com/JuliaAstro/FITSIO.jl/commit/f9445c755e89cad435393316c24789ec606dd5b1
On master
```julia
julia> f = tempname()
"/tmp/jl_06nrxc"
julia> FITSIO.fitswrite(f, Float64[1 2; 3 4]);
julia> ff = FITS(f, "r");
julia> v = zeros(4);
julia> @btime read!($(ff[1]), $v);
640.083 ns (5 allocations: 384 bytes)
```
After this PR
```julia
julia> @btime read!($(ff[1]), $v);
541.556 ns (4 allocations: 288 bytes)
```
=> Reduce allocations in read! if ndims don't match

src/image.jl, test/runtests.jl
Accept `Integer` indices (other than `Int`) in `read`, so now these work:
```julia
julia> filename = tempname();
julia> FITSIO.fitswrite(filename, collect(reshape(1:100, 10, 10)));
julia> f = FITS(filename, "r");
julia> read(f[1], Int8(1):Int8(2), :)
2×10 Matrix{Int64}:
1  11  21  31  41  51  61  71  81  91
2  12  22  32  42  52  62  72  82  92
julia> read(f[1], Int8(1):Int8(2), big(3))
2-element Vector{Int64}:
21
22
```
=> relax types of arguments to read

src/image.jl, test/runtests.jl
The PR is best viewed by ignoring the whitespace fixes. The main change is in the various `read!` functions that now accept an array with an eltype different from that of the image. This is supported by cfitsio through an internal conversion.
After this PR
```julia
julia> f = tempname()
"/tmp/jl_ILWosZ"
julia> FITSIO.fitswrite(f, [1 2; 3 4]);
julia> m = zeros(2,2);
julia> ff = FITS(f, "r");
julia> read!(ff[1], m)
2×2 Matrix{Float64}:
1.0  2.0
3.0  4.0
julia> m
2×2 Matrix{Float64}:
1.0  2.0
3.0  4.0
julia> eltype(ff[1])
Int64
```
Here `Int64` data is read into a `Float64` array. This used to error on master.
=> relax eltypes in inplace read

Project.toml, src/image.jl
This PR relies on https://github.com/JuliaAstro/CFITSIO.jl/pull/8, so tests will only pass with that PR merged and a version tagged.
On master and using the latest tagged CFITSIO:
```julia
julia> filename = tempname();
julia> FITSIO.fitswrite(filename, collect(reshape(1:10_000, 100, 100)));
julia> using BenchmarkTools
julia> g(f::FITS) = size(f[1]);  # runtime dispatch
julia> h(f::FITS) = size(f[1]::ImageHDU{Int,2}); # compile-time dispatch
julia> f = FITS(filename, "r");
julia> @btime g($f);
161.138 ns (2 allocations: 128 bytes)
julia> @btime h($f);
127.562 ns (1 allocation: 96 bytes)
```
After this PR:
```julia
julia> @btime g($f);
97.467 ns (1 allocation: 32 bytes)
julia> @btime h($f);
67.117 ns (0 allocations: 0 bytes)
```
With this, in-place read becomes allocation-free:
On master …
=> Use ndims in size to reduce allocations

docs/Project.toml, docs/src/api.md, src/FITSIO.jl, src/fits.jl, src/header.jl, src/image.jl, test/runtests.jl
This PR depends on https://github.com/JuliaAstro/CFITSIO.jl/pull/6, where the function to delete an HDU is added. Now it's possible to remove an HDU from a FITS file.
```julia
julia> f = FITS(tempname() * ".fits", "w");
julia> write(f, ones(1,1))
julia> write(f, ones(2,2))
julia> write(f, ones(3,3))
julia> deleteat!(f, 2)
File: /tmp/jl_XeX9WX.fits
Mode: "w" (read-write)
HDUs: Num  Name  Type   
1          Image  
2          Image  
julia> size(f[2])
(3, 3)
julia> deleteat!(f, 1) # deleting the primary HDU recreates one with minimal metadata and no image
File: /tmp/jl_XeX9WX.fits
Mode: "w" (read-write)
HDUs: Num  Name  Type   
1          Image  
2          Image  
julia> size(f[1])
()
julia> size(f[2])
(3, 3)
```
=> Add deleteat

src/image.jl
Leave it to CFITSIO.jl to decide if the sizes are passed as a tuple or a vector.
=> use higher-level method to create image in write

Project.toml, src/image.jl, test/runtests.jl
write an array to an existing `hdu` even if the `eltype`s don't match. The data is internally converted by cfitsio to the correct eltype.
=> write data of any eltype to an existing hdu

Project.toml, src/FITSIO.jl, src/image.jl, test/runtests.jl
This depends on https://github.com/JuliaAstro/CFITSIO.jl/pull/9, so tests will pass after that is merged and a version tagged.
After this, it's possible to conditionally disable the extended filename syntax through a keyword argument. This adds support for filenames with square brackets in them (originally raised as an issue in https://github.com/JuliaAstro/FITSIO.jl/issues/157). With the extended parser disabled, the filename string is not tokenized and is treated literally as the name of the file on disk. 
On master
```julia
julia> FITS(tempname()*"[1].fits", "w") do f
write(f, [1,2])
read(f[1])
end
ERROR: CFITSIO has encountered an error while processing /tmp/jl_gNF8za[1].fits. Error code 125: parse error in input file URL
```
After this PR
```julia
julia> FITS(tempname()*"[1].fits", …
```
=> conditionally disable the extended filename parser

src/header.jl, test/runtests.jl
In working on https://github.com/JuliaAstro/AstroImages.jl/issues/29, I found that for some images WCSLib could parse the headers in some FITS files just fine, but loading the headers with FITSIO and then calling `string` created headers that WCSLib could not read.
Doing a before and after diff, I found there were some minor differences in how string values are formatted.
This PR changes the formatting so that WCS.jl and WCSLib can read headers loaded by FITSIO from more images.
Before:
```
OBJECT  =                  ' ' / Name of the object observed
DATE    = '2009-09-03T04:30:56' / Date FITS file was generated
IRAF-TLM= '00:30:56 (03/09/2009)' / Time of last modification
EQUINOX =               2000.0 / Mean equinox
RADECSYS=               'ICRS' / Astrometric system
CTYPE1  = …
```
=> Adjust header output formatting for better compatibility

Project.toml, src/table.jl, test/runtests.jl
CFITSIO definitions for reference:
<https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node20.html>
Example file to reproduce error:
<https://data.sdss.org/sas/dr18/spectro/sdss/redux/v5_13_2/spectra/lite/3650/spec-3650-55244-0001.fits>
MWE/MRE:
```julia
using FITSIO
fits = FITS("spec-3650-55244-0001.fits")
hdu = fits["SPALL"]
read(hdu, "SPECOBJID")
```
This pr with https://github.com/JuliaAstro/CFITSIO.jl/pull/22 will fix error(s) including:
* `KeyError: key 80 not found`
* `MethodError: no method matching cfitsio_typecode(::Type{UInt64})`
=> Add missing data type (UInt64/Culonglong)

src/header.jl, test/runtests.jl
It's more convenient to provide all three (keys + values + comments) as a single array than separately.
=> add a more convenient FITSHeader constructor

Project.toml, src/FITSIO.jl, src/header.jl, src/table.jl, test/runtests.jl
This PR tries to reduce unsafe operations by ensuring that we call CFITSIO wrappers instead of directly dealing with pointers.
=> Avoid direct ccalls and call CFITSIO wrappers

test/runtests.jl
The leading whitespace is ignored by julia anyway, and this allows easier code folding.
=> Adjust whitespace in multiline-string header test

src/fits.jl, test/runtests.jl
This reduces code duplication. We also now throw a `BoundsError` if the indexing operation is out-of-bounds.
=> Consolidate `getindex` methods for `FITS`

src/image.jl, test/runtests.jl
CFITSIO interprets 0-dim arrays differently from Julia. In CFITSIO, a 0-dim array is empty, whereas in Julia, it has one element. Writing a 0-dim array to a fits file therefore fails, and reading one that has been written somehow leads to nonsensical results, as we deal with uninitialized memory.
In this PR, we improve the error message in `write`, and make `read` for a 0-dim image HDU return `nothing`. This matches the behavior of astropy, and is probably the only sensible answer.
=> Handle 0-dim images

src/image.jl
Remove the note about unsupported element types in the docstring of `write`. This works, but is a bit of a hack, so we should probably not be documenting it.
=> Remove note about unsupported element types

src/fits.jl, test/runtests.jl
Currently, we assert that the file is open in `summary` before reading fields from it. However, this obviously fails for a closed file. In this PR, we add a branch for a closed file, and change the assert to a check.
=> Fix `summary` for closed file
